### ISSUE TITLE
Is "in app updates" not yet supported in Android TV ?

### ISSUE THREAD

**Issue by xieenming** [android/tv-codelabs#1]
Hello, I would like to know if "in app updates" is not yet supported in Android TV.

I see https://developer.android.com/guide/playcore/in-app-updates that "Additionally, in-app updates are only supported for Android mobile devices, Android tablets, and ChromeOS devices.".

And on StackOverflow, there is a post : https://stackoverflow.com/questions/58230374/android-in-app-updates-api-cannot-work-on-the-android-tv-device

If it is not supported yet in Android TV, is there a plan for in app updates to be supported in Android TV in the future ?

Thanks a lot.

**Comment by chikoski** [comment]
HI @xieenming, 

Thanks for filing an issue here, but it look not related to the code in this repository. I am afraid that here is not the right place to ask your questions.

**Comment by xieenming** [comment]
@chikoski then where can I post the question ?
