### ISSUE TITLE
Inconsistency between the codelab and final code

### ISSUE THREAD

**Issue by WambuaSimon** [android/tv-codelabs#6]
The codelab used a non existent **CarouselSlide** composable while the final code simply uses a **Card** in the **CatalogBrowser** file. 
![image](https://github.com/android/tv-codelabs/assets/11309500/40a3bc71-a881-4124-b534-15896d690558)
![image](https://github.com/android/tv-codelabs/assets/11309500/2188b4db-421f-42fa-8572-7b4222601697)

**Comment by chikoski** [comment]
Apologies for my delayed response. CarouselSlide is no longer a part of tv-material library, and the codelab will be updated with the latest API. The solution code is also updated soon.
